user_name = input("What is your name?")
print("Welcome to my Band Name Generator,", user_name, "!")
user_city = input("Tell me the name of the city you grew up in.")
print(user_city, "sounds like a great place to grow up!")
user_pet = input("Now, please tell me your the name of your very first pet.")
print(user_pet, "!WOW!I love that name!")
print("Ooooo I've got it!")
print("Maybe you should call your band ", user_city, user_pet)
print("OR you could try ", user_pet, user_city)